image: gitpod/workspace-java-23
# image: condaforge/mambaforge:24.7.1-0

tasks:
- name: install mamba and multiqc
  init: |
    cd /workspace
    wget "https://github.com/conda-forge/miniforge/releases/download/24.3.0-0/Mambaforge-24.3.0-0-Linux-x86_64.sh"
    bash Mambaforge-24.3.0-0-Linux-x86_64.sh -b -p /workspace/mambaforge && rm Mambaforge-24.3.0-0-Linux-x86_64.sh
    /workspace/mambaforge/bin/mamba init bash
    source ${HOME}/.bashrc
    mamba create -n gbs_env -c bioconda multiqc -y 
    #    gp sync-done bundle  
    # - name: activate mamba
    #  init: gp sync-await bundle # Wait for previous 'inits' to complete
    #  command: |
    cd /workspace
    /workspace/mambaforge/bin/mamba init bash
    source ~/.bashrc 
    gp sync-done bundle
    #- name: install fastqc and stacks
    #  init: |
    #    gp sync-await bundle # Wait for previous 'inits' to complete
    mamba activate gbs_env
    mkdir software
    cd software
    wget "https://www.bioinformatics.babraham.ac.uk/projects/fastqc/fastqc_v0.12.1.zip"
    wget "https://catchenlab.life.illinois.edu/stacks/source/stacks-2.68.tar.gz"
    unzip fastqc_v0.12.1.zip
    tar -xvzf stacks-2.68.tar.gz
    cd stacks-2.68
    ./configure
    make
    export PATH=/workspace/bin:"$PATH"
    export PATH=/workspace/software/FastQC:"$PATH"
    export PATH=/workspace/software/stacks-2.66/bin:"$PATH"
    cd /workspace/gbs_workflow
    cd 00_fastq
    #download data
    wget "https://unimi2013-my.sharepoint.com/:u:/g/personal/chiara_paleni_unimi_it/EXb7WHDhaKVEjhxMiPfw_ZABZ6DhDM8UGmmPTr0pVBMJUw?e=AuVorb&download=1" -O Sal_subsample.tar
    tar -xvf Sal_subsample.tar
    rm Sal_subsample.tar
    cd ..

workspaceLocation: "/workspace"
